### ISSUE TITLE
MHX key removed?

### ISSUE THREAD

**Issue by lh110533** [svanheulen/mhef#10]
With your updating in 24 July,
When I write "Python dlc.py e X JPN q1010002.arc q1010002.arc"(encrypt)
It output:
Traceback (most recent call last):
  File "dlc.py", line 42, in <module>
    dc = mhef.n3ds.DLCXCipher(mhef.n3ds.MHX_JP)
TypeError: __init__() missing 1 required positional argument: 'key'

 and where can I write a key of mhx?

THX

**Comment by svanheulen** [comment]
It looks like you installed the new version of the `mhef` module but you're still using the old example scripts. The new example script for MHX quests is `examples\n3ds\dlcx.py` and it requires you to provide the key.

Since the key changes every 48 hours, it was useless to have it in the code because I had to constantly update them. You can get the key using the `tools\get_mhx_key.py` script with NTR CFW.

**Comment by lh110533** [comment]
Thank you so much ,my master!!!  I find a new key in your closed issues with your help, it's aslo worked!!!
